# Generated by Django 5.0.1 on 2024-02-02 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_project_date_project_project_startdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedetail',
            name='projects',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
