# Generated by Django 5.0.1 on 2024-02-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_employeedetail_projects_delete_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetail',
            name='salary',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='employeedetail',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
